---
AllCops:
  Exclude:
    - "**/node_modules/**/*"
    - "**/vendor/**/*"
    - "**/db/schema.rb"
  NewCops: enable
  TargetRubyVersion: 3.0
Layout/ClosingHeredocIndentation:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/PercentStringArray:
  Enabled: false
Lint/SafeNavigationChain:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateMethod:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Performance/Sum:
  Enabled: false
Performance/UnfreezeString:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Rails/Delegate:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Rails/NegateInclude:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/Presence:
  Enabled: false
Rails/Present:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/ThreeStateBooleanColumn:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Security/Eval:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-capybara
