# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.4.5"

gem "active_storage_validations"
gem "bcrypt"
gem "brakeman"
gem "browser"
gem "bundle-audit"
gem "bundler-audit"
gem "cloudflare-rails"
gem "code-ruby"
gem "dorian"
gem "dorian-arguments"
gem "dorian-to_struct"
gem "dotenv-rails"
gem "down"
gem "easy_translate"
gem "faker"
gem "heroicon"
gem "http_accept_language"
gem "image_processing"
gem "importmap-rails"
gem "irb"
gem "jbuilder"
gem "kamal"
gem "kaminari"
gem "local_time"
gem "mission_control-jobs"
gem "msgpack"
gem "net-http"
gem "open-uri"
gem "optparse"
gem "paper_trail"
gem "pg"
gem "phonelib"
gem "propshaft"
gem "public_suffix"
gem "puma"
gem "pundit"
gem "rack-attack"
gem "rails"
gem "rails-i18n"
gem "recaptcha"
gem "redis"
gem "rpush"
gem "rubocop-capybara"
gem "rubocop-performance"
gem "rubocop-rails"
gem "rubocop-rake"
gem "search_rails"
gem "slim-rails"
gem "solid_cable"
gem "solid_cache"
gem "solid_errors"
gem "solid_queue"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "thruster"
gem "turbo-rails"
gem "zxcvbn-ruby"

gem "i18n-tasks", "~> 1.0"
