# frozen_string_literal: true

source "https://rubygems.org"

git_source(:dorian) { |name| "https://github.com/dorianmariecom/#{name}" }
git_source(:rails) { |name| "https://github.com/rails/#{name}" }
git_source(:hotwired) { |name| "https://github.com/hotwired/#{name}" }

ruby "3.4.5"

gem "bcrypt"
gem "brakeman"
gem "browser"
gem "bundle-audit"
gem "bundler-audit"
gem "cloudflare-rails"
gem "code-ruby"
gem "commonmarker"
gem "database_cleaner", "2.1.0" # fix for undefined method 'count' for nil
gem "dorian"
gem "dorian-arguments"
gem "dorian-to_struct"
gem "dotenv-rails"
gem "easy_translate"
gem "factory_bot_rails"
gem "faker"
gem "heroicon"
gem "http_accept_language"
gem "image_processing"
gem "importmap-rails"
gem "irb"
gem "jbuilder"
gem "kamal"
gem "kaminari"
gem "local_time"
gem "mission_control-jobs"
gem "msgpack"
gem "net-http"
gem "open-uri"
gem "optparse"
gem "paper_trail"
gem "pg"
gem "phonelib"
gem "propshaft"
gem "public_suffix"
gem "puma"
gem "pundit"
gem "rack-attack"
gem "rails"
gem "rails-i18n"
gem "recaptcha"
gem "redis"
gem "rpush"
gem "rspec-rails"
gem "rubocop-capybara"
gem "rubocop-factory_bot"
gem "rubocop-performance"
gem "rubocop-rails"
gem "rubocop-rake"
gem "rubocop-rspec"
gem "rubocop-rspec_rails"
gem "search_rails"
gem "slim-rails"
gem "solid_cable"
gem "solid_cache"
gem "solid_errors"
gem "solid_queue"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "thruster"
gem "turbo-rails"
gem "zxcvbn-ruby"
