---
development:
  cleaning:
    class: CleaningJob
    queue: default
    schedule: every 5 minutes
production:
  cleaning:
    class: CleaningJob
    queue: default
    schedule: every 5 minutes
  scheduling:
    class: SchedulingJob
    queue: scheduling
    schedule: every second
staging:
  cleaning:
    class: CleaningJob
    queue: default
    schedule: every 5 minutes
  scheduling:
    class: SchedulingJob
    queue: scheduling
    schedule: every second
